site_name: IDendro
theme:
  name: "material"
  highlightjs: true
  icon:
    admonition:
      tip: octicons/squirrel-16
  hljs_languages:
    - python

plugins:
  - mkdocstrings

nav:
  - Home page: index.md  
  - How-To Guides:
    - Getting started: getting-started.md
    - Customizing looks: customizing-looks.md
    - Using in Streamlit: streamlit.md
  - Reference:
    - Creating dendrogram objects: reference.md
    - Plotting dendrograms: dendrogram.md
    - Callback functions for formatting: callbacks.md
    - Clustering Info Container: cluster-info-container.md
    - Data Containers: data_containers.md
    

watch:
  - idendro